#Here we can paste small parts of the code and test them

def test_rectangular_shape():
   #Some basic movements of the robot programmed in UR-SCRIPT (Rectangular-shape frames first)
   #How to do a rectangular movement test:

   i= 0
   j =0

   startpoint = get_actual_tcp_pose()
   waypoint_1 = pose_add(startpoint, p[0.2,0,0,0,0,0])
   waypoint_2 = pose_add(waypoint_1, p[0,-0.2,0,0,0,0])
   waypoint_3 = pose_add(waypoint_2, p[-0.2,0,0,0,0,0])
   waypoint_4 = pose_add(waypoint_3, p[0,0.2,0,0,0,0])

   while i<10
      movel(waypoint_1, a=1.0, v=0.1)
      movel(waypoint_2, a=1.0, v=0.1)
      movel(waypoint_3, a=1.0, v=0.1)
      movel(waypoint_4, a=1.0, v=0.1)
      i = i + 1
      end


   #Adapt this rectangular movement to each frame with the especific dimensions (Cognex or OpenCV)
