

port = 10000
ip = "192.168.0.2"
name_socket = "server"

textmsg("Attempting to connect...")
socket = socket_open(ip, port, name_socket)

while True:
    if socket:
        textmsg("Connected!")
        textmsg(socket_read_string(name_socket))
        break
    end
    textmsg("Connection failed!")
    textmsg("Attempting to connect...")
    socket = socket_open(ip, port, name_socket) 
    sleep(1)
end

halt